"""
Integration helpers for Tier 2-4 features in query.py

Handles:
- Zoom-level synthesis (Tier 2)
- Branching presentation (Tier 3)
- Code execution (Tier 4)
"""

from __future__ import annotations

import logging
from typing import Optional
from .llm.synthesis import synthesis_at_zoom_level, global_synthesis_llm
from .llm.synthesis_levels import ZoomLevel, get_zoom_config, get_zoom_options
from .core.branching import format_branching_for_user, should_present_branching
from .core.branching_session import get_branching_session_manager, BranchingSession
from .core.observability import get_observability_tracker, MetricType
from .core.types import Learning

logger = logging.getLogger(__name__)


async def synthesis_with_zoom(
    query: str,
    learnings: list[Learning],
    zoom_level: int = 0,
    client=None,
    prompt_specificity: str = "standard",
) -> tuple[str, dict]:
    """
    Generate answer at specified zoom level.
    
    Args:
        query: User's question
        learnings: Retrieved context
        zoom_level: 0=overview, 1=focused, 2=comprehensive
        client: LLM client
        prompt_specificity: How specific is the query?
    
    Returns:
        (answer, zoom_options_dict)
    """
    if zoom_level == 0:
        zoom_str = "overview"
    elif zoom_level == 1:
        zoom_str = "focused"
    else:
        zoom_str = "comprehensive"
    
    logger.debug(f"Synthesizing at zoom level {zoom_level} ({zoom_str})")
    
    # Use zoom-aware synthesis if available
    try:
        answer = await synthesis_at_zoom_level(
            query=query,
            learnings=learnings,
            zoom_level=zoom_str,
            client=client,
        )
    except Exception as e:
        logger.warning(f"Zoom synthesis failed: {e}, falling back to standard")
        answer = await global_synthesis_llm(
            query, learnings, client=client,
            prompt_specificity=prompt_specificity,
        )
    
    # Build zoom options
    zoom_options = get_zoom_options(zoom_level)
    
    # Track in observability
    tracker = get_observability_tracker()
    tracker.record_event(
        MetricType.THINKING_DEPTH_ADJUSTED,
        value=zoom_level,
        domain="zoom_level",
        details={"source": "user_requested"}
    )
    
    return answer, zoom_options


def should_present_branching_for_result(
    pivot_decision,
    branching_options: list,
    branching_enabled: bool = True,
) -> bool:
    """
    Decide if we should present branching options to the user.
    
    Args:
        pivot_decision: Result from pivot loop
        branching_options: Options generated by pivot
        branching_enabled: Feature flag
    
    Returns:
        True if should present to user
    """
    if not branching_enabled or not branching_options:
        return False
    
    # Only present if we have multiple valid options
    if len(branching_options) < 2:
        return False
    
    # Check confidence gap
    confidences = [opt.confidence for opt in branching_options]
    gap = confidences[0] - confidences[1]
    
    should_present = gap < 0.25 and confidences[0] < 0.85
    
    logger.debug(f"Branching presentation: gap={gap:.3f}, present={should_present}")
    return should_present


def handle_branching_presentation(
    query: str,
    branching_options: list,
    branching_enabled: bool = True,
) -> tuple[Optional[str], Optional[str], list]:
    """
    Present branching options to user and prepare for multi-turn interaction.
    
    Args:
        query: Original query
        branching_options: Options to present
        branching_enabled: Feature flag
    
    Returns:
        (formatted_message, session_id, branching_options)
    """
    if not branching_enabled or not branching_options:
        return None, None, []
    
    # Format for user
    message = format_branching_for_user(branching_options)
    
    # Create session
    manager = get_branching_session_manager()
    import uuid
    session_id = str(uuid.uuid4())[:8]
    
    session = manager.create_session(session_id, query, branching_options)
    
    # Track event
    tracker = get_observability_tracker()
    tracker.record_event(
        MetricType.BRANCHING_PRESENTED,
        value=len(branching_options),
        details={"session_id": session_id}
    )
    
    logger.info(f"Presented {len(branching_options)} branches to user (session: {session_id})")
    
    return message, session_id, branching_options
